name: Daily Scrapers

on:
  schedule:
    - cron: '0 3 * * *'  # 03:00 UTC daily
  workflow_dispatch: {}

jobs:
  run-scrapers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Run scrapers against production API
        env:
          API_URL: https://eventpulse-nc-backend-ea4ecf265b40.herokuapp.com
        run: |
          python scraper/run_all_scrapers.py

